### ISSUE TITLE
Error when using functionals from libxc

### ISSUE THREAD

**Issue by hsulab** [pekkosk/hotbit#30]
Dear Developers and Users, 

I would like to compare the electronic parameters generated from various functionals. But I have ran into some errors in using both LDA and GGA functionals.

About codes, I use openblas to compile hotbit and install the pylibxc based on libxc-5.0.0.

Using LDA PW92 from libxc,
```
>>> calc = KSAllElectron('Pt', scalarrel = True, xc = 'pw92')
>>> calc.run()
*******************************************
Kohn-Sham all-electron calculation for Pt
*******************************************
Using scalar relativistic corrections.
max 5 nodes, 3000 grid points
Pt xc=pw92 charge=0.0 conf:none

Start iteration...
iter   0, dn=1.5e+02>1.0e-07, max 14 sp-iter
iter  10, dn=2.3e+00>1.0e-07, max 10 sp-iter
Traceback (most recent call last):
  File "/home/hotbit/parametrization/atom.py", line 330, in run
    d_enl_max, itmax=self.solve_eigenstates(it)
  File "/home/hotbit/parametrization/atom.py", line 419, in solve_eigenstates
    assert c0[-2]<0 and c0[-1]<0
AssertionError
```

Using GGA PBE from libxc,
```
>>> calc = KSAllElectron('Pt', scalarrel = True, xc = 'pbe')
>>> calc.run()
*******************************************
Kohn-Sham all-electron calculation for Pt
*******************************************
Using scalar relativistic corrections.
max 5 nodes, 3000 grid points
Pt xc=pbe charge=0.0 conf:none

Start iteration...
Traceback (most recent call last):
  File "/home/hotbit/parametrization/atom.py", line 326, in run
    self.veff=self.mix*self.calculate_veff()+(1-self.mix)*self.veff
  File "/home/hotbit/parametrization/atom.py", line 263, in calculate_veff
    self.vxc=self.xcf.vxc(self.dens)
  File "/home/hotbit/parametrization/pylibxc_interface.py", line 90, in vxc
    if self._xGGA: v_x -= self.v_gga(res['vsigma'][0], drho_dr)
ValueError: non-broadcastable output operand with shape (1,) doesn't match the broadcast shape (3000,)
```

Could you give me some advice on these errors? Is there a docker for hotbit+libxc to run some calculations successfully?

Many thanks,
Jiayan

**Comment by hsulab** [comment]
Another error for Carbon using pw92,
```
*******************************************
Kohn-Sham all-electron calculation for  C
*******************************************
Using scalar relativistic corrections.
max 1 nodes, 1000 grid points
C xc=pw92 charge=0.0 conf:none

Start iteration...
iter   0, dn=4.1e+00>1.0e-07, max 7 sp-iter
iter  10, dn=9.6e-02>1.0e-07, max 5 sp-iter
iter  20, dn=6.4e-03>1.0e-07, max 4 sp-iter
iter  30, dn=3.4e-04>1.0e-07, max 3 sp-iter
iter  40, dn=1.9e-05>1.0e-07, max 3 sp-iter
iter  50, dn=1.3e-06>1.0e-07, max 2 sp-iter
iter  60, dn=1.1e-07>1.0e-07, max 2 sp-iter
Traceback (most recent call last):
  File "/home/hotbit/parametrization/atom.py", line 347, in run
    self.calculate_energies(echo=True)
  File "/home/hotbit/parametrization/atom.py", line 177, in calculate_energies
    self.exc=self.xcf.exc(self.dens)
  File "/home/hotbit/parametrization/pylibxc_interface.py", line 68, in exc
    e_xc = e_x + e_c
NameError: name 'e_x' is not defined
```

It seems there is something wrong with the functionals using separate exchange and correlation.

**Comment by Yinhe-Wang** [comment]
Hi Jiayan and developer, 

I came across the same issue while trying to use PBE functional from libxc and I got the same error as you did. Did you find the solution to this problem? If yes, could you please give me some advice?

Many thanks.

**Comment by GengSS** [comment]
Hi,
I encountered into the same error when using PBE functional from pylibxc.
Any suggestions are appreciated!

Best,
Geng

**Comment by hsulab** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi Geng,I did not fix this bug and it seems that hotbit was not under maintenance. If you’d like to generate the electronic part of Slater-Koster table (that is not very easy), an alternative choice is using https://github.com/dftbplus/skprogs.git, which is by one core developers of DFTB+, and the latest version supports libXC. By the way, the difference of electronic part between PW91 and PBE is very small. In practice, you can fit electronic part with PW92 while repulsion part with PBE results.All the best,Jiayan

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        05/10/2022 14:35
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Jiayan ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [pekkosk/hotbit] Error when using functionals from libxc (#30)
        
      
    
  
  
Hi,
I encountered into the same error when using PBE functional from pylibxc.
Any suggestions are appreciated!
Best,
Geng
